# Generated by Django 3.1.4 on 2021-01-06 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=600)),
                ('length', models.IntegerField(max_length=100)),
                ('views', models.IntegerField(max_length=15)),
                ('date', models.DateField()),
                ('ytType', models.CharField(max_length=30)),
                ('youtube_cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.youtubecache')),
            ],
        ),
    ]
