# Generated by Django 3.1.4 on 2021-01-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoYT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidID', models.CharField(max_length=600)),
                ('desc', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=600)),
                ('length', models.CharField(max_length=600)),
                ('views', models.IntegerField()),
                ('date', models.DateField()),
                ('ytType', models.CharField(max_length=30)),
            ],
        ),
    ]
