# Generated by Django 3.1.4 on 2021-01-08 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='YTVideo',
        ),
    ]
