# Generated by Django 3.1.4 on 2021-01-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210109_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoyt',
            name='desc',
            field=models.TextField(),
        ),
    ]
