# Generated by Django 3.1.4 on 2021-01-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210107_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=600)),
                ('length', models.IntegerField(max_length=100)),
                ('views', models.IntegerField(max_length=15)),
                ('date', models.DateField()),
                ('ytType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_cache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.youtubecache'),
        ),
    ]
